const products = [
  {
    _id: "1",
    name: "Origami Vase (cream)",
    image: "/images/origami1.jpg",
    description: "Origami vase made from paper ",
    brand: "paper",
    category: "handmade",
    price: 200,
    countInStock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Origami Vase (brown)",
    image: "/images/origami2.jpg",
    description: "Origami vase made from paper ",
    brand: "paper",
    category: "handmade",
    price: 200,
    countInStock: 3,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: "3",
    name: "Origami Vase (blue)",
    image: "/images/origami3.jpg",
    description: "Origami vase made from paper ",
    brand: "paper",
    category: "handmade",
    price: 100,
    countInStock: 4,
    rating: 4.0,
    numReviews: 5,
  },
  {
    _id: "4",
    name: "Origami Vase (brown/gray)",
    image: "/images/origami4.jpg",
    description: "Origami vase made from paper ",
    brand: "paper",
    category: "handmade",
    price: 500,
    countInStock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Origami Vase (red)",
    image: "/images/origami5.jpg",
    description: "Origami vase made from paper ",
    brand: "paper",
    category: "handmade",
    price: 499.99,
    countInStock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "Origami Vase (random)",
    image: "/images/origami2.jpg",
    description: "Origami vase made from paper ",
    brand: "paper",
    category: "handmade",
    price: 59,
    countInStock: 1,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
